# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dVduc_czMmNutsWeIAMNqmDA3fR1Qx6
"""

from flask import Flask, render_template, send_file, abort
import os
from nbconvert import HTMLExporter
import nbformat

app = Flask(__name__)
NOTEBOOKS_DIR = "notebooks"

# List all notebooks
@app.route("/")
def index():
    notebooks = []
    for file in os.listdir(NOTEBOOKS_DIR):
        if file.endswith(".ipynb"):
            notebooks.append(file)
    return render_template("index.html", notebooks=notebooks)

# Render a single notebook as HTML
@app.route("/notebook/<name>")
def show_notebook(name):
    notebook_path = os.path.join(NOTEBOOKS_DIR, name)
    if not os.path.exists(notebook_path):
        abort(404)

    with open(notebook_path, "r") as f:
        notebook = nbformat.read(f, as_version=4)
        html_exporter = HTMLExporter()
        (body, _) = html_exporter.from_notebook_node(notebook)
        return render_template("notebook.html", content=body, notebook_name=name)

# Download the original .ipynb file
@app.route("/download/<name>")
def download_notebook(name):
    notebook_path = os.path.join(NOTEBOOKS_DIR, name)
    if not os.path.exists(notebook_path):
        abort(404)
    return send_file(notebook_path, as_attachment=True)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)

